### PR TITLE
Contoso University sample web api

### PR DESCRIPTION
**Pull request by blakeSaucier**
An implementation of the popular demo project 'Contoso University' with Language-ext.

The motivation for this project was the desire to see Language Ext working in a simple end to end web api. A couple folks have requested seeing this in action:
#606 
#556 

The project combines CQRS (making use of MediatR) with Language Ext. All commands and queries are Record<T> types (from Language Ext). The handlers contain the validation, mapping, and data persistence work - all of which is done via the functional monads offered by Language Ext.

Some Language Ext features being used:
- Option based data access/repositories
- Using Either<L, R> 
- Using Validation<FAIL, SUCCESS>
- Working with Tasks
- Immutable Record<T> types
- Applicative Validation
- Unit testing and verifying methods that return monadic results

There is a good portion of code in the Infrastructure project which is done in an imperative, non-functional style. This is due to the limitations of working with Entity Framework and the surrounding code (entity configuration, repositories using dbContext, data seeding).

I enjoyed building out this project, I hope it's in alignment with your vision for Language-ext and helps newcomers.

### CODE REVIEW

**Comment by louthy** [comment]
Wow! This is great.  I can see some areas where it could be taken further, but yeah a good start I reckon.

One thing that needs to be checked is whether there’s a license that needs adhering to, do you have a link to the original?

**Comment by aramkoukia** [comment]
wow, I have been waiting for this for so long. Thanks @blakeSaucier and of course thanks @louthy

**Comment by blakeSaucier** [comment]
The inspiration for the project came from [jbogard's dotnet core example](https://github.com/jbogard/ContosoUniversityDotNetCore-Pages). You'll notice that `DbInitializer.cs` is very similar - I wanted to keep the data and schema the same. This project is licensed under the MIT license.

Yes, there are areas that could be taken further. I decided to create the PR in its current state as I believe this shows a valid example of where Language-ext would fit (and help) in a web application built with dotnet core.

**Comment by louthy** [comment]
Good stuff, I’ll try and get it reviewed over the next few days

**Comment by betoramiz** [comment]
Amazing!

**Pull request merged**
