### PR TITLE
Add Prelude.parseEnumIgnoreCase<TEnum>(string value)

### PR DESCRIPTION
**Pull request by jltrem**
This addresses issue #669

### CODE REVIEW

**Comment by louthy** [comment]
btw, I haven't forgotten about this, I'm just not 100% on the need for separate functions that capture the ignore-case flag, and right now it's not top of my mind to care too much about it, so I'm pressing pause on this PR until I think about it fully.

**Comment by jltrem** [comment]
thanks, Paul.  It seemed a bit dubious to me too.  FWIW the request came from someone on my team implementing config file parsing. (He hadn't been keen on using language-ext until recently, so I was pleased he brought it up.)  If you think of a better approach I'd be happy to rework it.

**Comment by louthy** [comment]
@jltrem Hi Joe, I think I'd prefer there to just be one `parseEnum` with an `ignoreCase` boolean, like the original.

**Comment by jltrem** [comment]
Not sure I follow you on "like the original".  Do you mean change the existing `public static Option<TEnum> parseEnum<TEnum>(string value)` to have an ignoreCase boolean?  If so, would you want it to have a default `false` to avoid a breaking change?

**Comment by louthy** [comment]
Sorry to be unclear, I forgot the `parseEnum` already existed.  I think probably have.  I'm changing my mind now, because there's always value to single argument functions in functional programming.  So, I think I'll accept as is

**Comment by louthy** [comment]
Thanks @jltrem

**Pull request merged**
