### PR TITLE
Add file move to FileIO

### LINKED ISSUE #1174: FileIO move missing?
I am missing the `File.Move` equivalent in FileIO (https://github.com/louthy/language-ext/blob/main/LanguageExt.Sys/Traits/FileIO.cs).
Is it missing on purpose?

### PR DESCRIPTION
**Pull request by timmi-on-rails**
Fix  #1174

### CODE REVIEW

**Review by bmazzarol — COMMENTED** [review]
Should move also be exposed on the static File module?

Just did not see it in the PR.

**Comment by timmi-on-rails** [comment]
Oops, forgot about it.
Will complete later.

**Comment by timmi-on-rails** [comment]
@bmazzarol I finally fixed it. Anything else?

**Review by bmazzarol — APPROVED** [review]
LGTM

**Comment by louthy** [comment]
I'm closing PRs that have conflicts because of the major v5 refactor.  

This still isn't supported, so if you feel like re-pushing, I'll accept.  Sorry for the delay!

**Pull request closed without merging**
